[package]
name = "runner"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
ethrex-levm.workspace = true
ethrex-vm.workspace = true
ethrex-common.workspace = true
ethrex-storage.workspace = true
ethrex-blockchain.workspace = true
hex.workspace = true
bytes.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
json5 = "0.4.1"
clap.workspace = true
log = "0.4.27"
env_logger = "0.11.8"
num-bigint = "0.4.6"
num-traits = "0.2.19"
rustc-hash.workspace = true

[lints]
workspace = true
