[package]
name = "ethrex-monitor"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
ethrex-storage-rollup.workspace = true
ethrex-storage.workspace = true
ethrex-rpc.workspace = true
ethrex-common.workspace = true
ethrex-sdk.workspace = true
ethrex-l2-common.workspace = true
ethrex-rlp.workspace = true
ethrex-config.workspace = true

spawned-concurrency.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true

crossterm = { version = "0.29.0", features = ["event-stream"] }
ratatui = "0.29.0"
tui-big-text = "0.7.1"
tui-scrollview = "0.5.1"
tui-logger.workspace = true
tabwriter = "1.4.1"
color-eyre = "0.6.5"
reqwest.workspace = true
tracing.workspace = true
thiserror.workspace = true
hex.workspace = true
chrono = "0.4.42"
secp256k1.workspace = true
bytes.workspace = true

[lib]
path = "lib.rs"
