[package]
name = "ethrex-rlp"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
tinyvec = "1.6.0"
thiserror.workspace = true
bytes.workspace = true
hex.workspace = true
lazy_static.workspace = true
ethereum-types.workspace = true
snap.workspace = true

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
ethrex-common = { workspace = true }
ethrex-p2p = { workspace = true }
ethrex-trie = { workspace = true }

[lib]
path = "./rlp.rs"

[lints]
workspace = true
