[package]
name = "ethrex-rlp"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
tinyvec = "1.6.0"
thiserror.workspace = true
bytes.workspace = true
hex.workspace = true
lazy_static.workspace = true
ethereum-types.workspace = true
snap.workspace = true

[dev-dependencies]
hex-literal.workspace = true
criterion = { version = "0.7.0", features = ["html_reports"] }
ethrex-common.workspace = true
ethrex-p2p.workspace = true
rand.workspace = true

[lib]
path = "./rlp.rs"

[lints]
workspace = true

[[bench]]
name = "decode"
harness = false

[[bench]]
name = "encode"
harness = false
