[package]
name = "ethrex-rlp"
version.workspace = true
edition.workspace = true

[dependencies]
tinyvec.workspace = true
thiserror.workspace = true
bytes.workspace = true
hex.workspace = true
lazy_static.workspace = true
ethereum-types.workspace = true
snap.workspace = true

[dev-dependencies]
hex-literal.workspace = true
[lib]
path = "./rlp.rs"
