[package]
name = "ethrex-rlp"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
tinyvec = "1.6.0"
thiserror.workspace = true
bytes.workspace = true
hex.workspace = true
lazy_static.workspace = true
ethereum-types.workspace = true
snap.workspace = true

[dev-dependencies]
hex-literal.workspace = true
ethereum-types.workspace = true

[[test]]
name = "rlp_tests"
path = "tests/tests.rs"

[lib]
path = "./rlp.rs"

[lints]
workspace = true
