[package]
name = "zkvm-pico-program"
verison = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
pico-sdk = { git = "https://github.com/brevis-network/pico" }

ethrex-common = { path = "../../../../../../common", default-features = false }
ethrex-storage = { path = "../../../../../../storage", default-features = false }
ethrex-rlp = { path = "../../../../../../common/rlp" }
ethrex-vm = { path = "../../../../../../vm", default-features = false }
ethrex-blockchain = { path = "../../../../../../blockchain", default-features = false }
ethrex-l2-common = { path = "../../../../../common", default-features = false }

guest_program = { path = "../../", default-features = false}

rkyv = { version = "0.8.10", features = ["std", "unaligned"] }

[patch.crates-io]
sha2 = { git = "https://github.com/brevis-network/hashes.git", package = "sha2", branch = "sha2-0.10.8-v1.0.0"}
sha3 = { git = "https://github.com/brevis-network/hashes.git", branch = "sha3-0.10.8-v1.0.0"}
tiny-keccak = { git = "https://github.com/brevis-network/tiny-keccak", branch = "patch-v1.0.0" }
bn = { git = "https://github.com/brevis-network/bn", branch = "patch-v1.0.1", package = "substrate-bn" }
bls12_381 = { git = "https://github.com/brevis-network/bls12_381", branch = "patch-v1.0.1" }
kzg-rs = { git = "https://github.com/brevis-network/kzg-rs.git", branch = "pico" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = true
embed-bitcode = true
