[package]
name = "ethrex-sdk"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
ethrex-common = { workspace = true, default-features = false }
ethrex-l2-common = { workspace = true, default-features = false }
ethrex-rpc = { workspace = true, default-features = false }
ethrex-l2-rpc = { workspace = true, default-features = false }
ethrex-sdk-contract-utils = { path = "contract_utils" }

ethereum-types.workspace = true
tokio.workspace = true
hex.workspace = true
secp256k1.workspace = true      # FIXME
itertools = "0.13.0"
thiserror.workspace = true
serde_json.workspace = true
serde.workspace = true
tracing.workspace = true
ethrex-rlp.workspace = true
bytes.workspace = true
reqwest.workspace = true
eyre.workspace = true
lazy_static.workspace = true

[lib]
name = "ethrex_l2_sdk"
path = "src/sdk.rs"

[build-dependencies]
ethrex-sdk-contract-utils = { path = "contract_utils" }
hex.workspace = true

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
as_conversions = "deny"
unnecessary_cast = "warn"
panic = "deny"

[features]
default = ["l1"]

l1 = ["ethrex-common/l1", "ethrex-rpc/l1", "ethrex-l2-common/l1"]
sp1 = [
    "ethrex-common/sp1",
    "ethrex-l2-common/sp1",
    "ethrex-rpc/sp1",
    "ethrex-l2-rpc/sp1",
]
risc0 = [
    "ethrex-common/risc0",
    "ethrex-l2-common/risc0",
    "ethrex-rpc/risc0",
    "ethrex-l2-rpc/risc0",
]
