[package]
name = "geth2ethrex"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
ethrex-common.workspace = true
ethrex-storage = { workspace = true, features = ["rocksdb"] }
ethrex-rlp.workspace = true
ethrex-trie.workspace = true
ethrex-config.workspace = true

anyhow.version = "1.0.100"
clap = { workspace = true, features = ["string"] }
clap_complete.workspace = true
eyre.workspace = true
rocksdb.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["rt"] }
tracing.workspace = true
tracing-subscriber.workspace = true
snap.workspace = true
