[package]
name = "ethrex-threadpool"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true

[lib]
path = "concurrency.rs"

[dependencies]
crossbeam.workspace = true

[lints]
workspace = true
