[package]
name = "ethrex-guest-l2"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ethrex-guest-common.workspace = true
ethrex-common = { path = "../../common", default-features = false }
ethrex-crypto = { path = "../../common/crypto", default-features = false }
ethrex-vm = { path = "../../vm", default-features = false }
ethrex-rlp = { path = "../../common/rlp", default-features = false }
ethrex-l2-common = { path = "../../l2/common", default-features = false }
rkyv = { version = "0.8.10", default-features = false, features = ["std", "unaligned"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_with = { version = "3.11.0", default-features = false }
bytes = { version = "1.6.0", default-features = false }
thiserror.workspace = true
