[package]
name = "loc"
edition.workspace = true
version.workspace = true

[dependencies]
tokei.workspace = true
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
clap_complete.workspace = true
colored.workspace = true
spinoff.workspace = true
prettytable.workspace = true