[package]
version = "9.0.0"
name = "ethrex-guest-zisk"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace]

[dependencies]
ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git", tag = "v0.15.0" }
sha2 = "0.10.9"
rkyv = { version = "0.8.10", features = ["std", "unaligned"] }

ethrex-guest-program = { path = "../../", default-features = false }
ethrex-vm = { path = "../../../vm", default-features = false, features = [
    "zisk",
] }
ethrex-common = { path = "../../../common", default-features = false, features = [
    "zisk",
] }

[patch.crates-io]
sha2 = { git = "https://github.com/0xPolygonHermez/zisk-patch-hashes.git", tag = "patch-sha2-0.10.9-zisk-0.15.0" }
sha3 = { git = "https://github.com/0xPolygonHermez/zisk-patch-hashes.git", tag = "patch-sha3-0.10.8-zisk-0.15.0" }
k256 = { git = "https://github.com/0xPolygonHermez/zisk-patch-elliptic-curves.git", tag = "patch-k256-0.13.4-zisk-0.15.0" }
substrate-bn = { git = "https://github.com/0xPolygonHermez/zisk-patch-bn.git", tag = "patch-0.6.0-zisk-0.15.0" }
sp1_bls12_381 = { git = "https://github.com/0xPolygonHermez/zisk-patch-bls12-381", tag = "patch-0.8.0-zisk-0.15.0" }
tiny-keccak = { git = "https://github.com/0xPolygonHermez/zisk-patch-tiny-keccak/", tag = "patch-2.0.2-zisk-0.15.0" }
kzg-rs = { git = "https://github.com/0xPolygonHermez/zisk-patch-kzg/", tag = "patch-0.2.7-zisk-0.15.0" }

[features]
l2 = ["ethrex-guest-program/l2"]
