- name: Ethrex Prover SP1
  hosts: prover_sp1
  become: true
  vars:
    ansible_ssh_user: admin
    ethrex_dir: "/home/{{ ansible_user }}/ethrex"
    ethrex_version: "v0.0.1-rc.1"

  tasks:
    - name: Get Docker GPG keyring
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
        filename: docker
        state: present
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Ensure Docker service is running and enabled
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      user:
        name: "{{ user }}"
        groups: docker
        append: yes
      vars:
        user: app

    - name: Make directories
      file:
        path: "{{ ethrex_dir }}/bin"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"

    - name: Download ethrex prover SP1
      become: false
      get_url:
        url: https://github.com/lambdaclass/ethrex/releases/download/{{ ethrex_version }}/ethrex_prover_sp1-linux_{{ ansible_architecture }}
        dest: "{{ ethrex_dir }}/bin/ethrex_prover"
        mode: "0744"

    - name: Install ethrex prover SP1 service
      template:
        src: services/ethrex-prover.service.j2
        dest: /etc/systemd/system/ethrex-prover.service
      vars:
        ethrex_sequencer_address: "{{ lookup('env', 'ETHREX_SEQUENCER_ADDRESS', default='127.0.0.1') }}"
        ethrex_sequencer_port: "{{ lookup('env', 'ETHREX_SEQUENCER_PORT', default='3900') }}"

    - name: Start ethrex prover SP1
      systemd:
        name: ethrex-prover
        state: started
        enabled: true
        daemon_reload: true
