[package]
name = "ethrex-trie"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true
license.workspace = true

[dependencies]
ethrex-crypto.workspace = true
ethrex-rlp.workspace = true

ethereum-types.workspace = true
anyhow = "1.0.86"
bytes.workspace = true
tracing.workspace = true
thiserror.workspace = true
hex.workspace = true
serde.workspace = true
serde_json = "1.0.117"
smallvec = { version = "1.10.0", features = ["const_generics", "union"] }
digest = "0.10.6"
lazy_static.workspace = true
crossbeam.workspace = true
rayon.workspace = true
rustc-hash.workspace = true
rkyv.workspace = true

[features]
default = []

[lib]
path = "./trie.rs"

[lints]
workspace = true
