apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prom-001
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 2 
    jsonData:
      # Scrape time interval should be 5s.
      timeInterval: 5s
      httpMethod: POST
    readOnly: false
    editable: true
