[package]
version = "9.0.0"
name = "ethrex-guest-openvm"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace]

[dependencies]
openvm = { git = "https://github.com/openvm-org/openvm.git", features = [
    "std",
], tag = "v1.4.1" }
openvm-keccak256 = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.4.1" }
openvm-k256 = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.4.1", package = "k256" }
openvm-ecc-guest = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.4.1" }
openvm-algebra-guest = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.4.1" }
rkyv = "0.8.10"

ethrex-vm = { path = "../../../vm", default-features = false, features = [
    "openvm",
] }
ethrex-common = { path = "../../../common", default-features = false, features = [
    "openvm",
] }

ethrex-guest-program = { path = "../..", default-features = false }

[features]
l2 = ["ethrex-guest-program/l2"]
