[package]
name = "opcode_bench"
version = "0.1.0"
edition = "2024"
authors = ["LambdaClass"]

[workspace]

[dependencies]
ethrex-levm = { path = "../../" }
ethrex-vm = { path = "../../.." }
ethrex-common = { path = "../../../../common" }
ethrex-storage = { path = "../../../../storage" }
ethrex-blockchain = { path = "../../../../blockchain" }
rustc-hash = "2.1.1"
hex = "0.4.3"
bytes = { version = "1.6.0", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[[bin]]
name = "opcode_bench"
path = "src/main.rs"
