- name: Database Setup
  hosts: database
  become: true
  vars:
    ansible_ssh_user: admin
    postgresql_version: 17
    pg_user: "{{ lookup('env', 'PGUSER') | default('ethrex') }}"
    pg_pass: "{{ lookup('env', 'PGPASSWORD') | default('lambda') }}"
    pg_db: "blockscout"

  tasks:
    - name: Install ACL package
      apt:
        name: 
          - acl
        state: present

    - name: Add PostgreSQL GPG key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        keyring: /etc/apt/trusted.gpg.d/postgresql.gpg
        state: present

    - name: Add PostgreSQL repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main"
        state: present
        filename: pgdg

    - name: "Install PostgreSQL {{ postgresql_version }}"
      apt:
        name: "postgresql-{{ postgresql_version }}"
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL is running
      systemd:
        name: postgresql
        state: started
        enabled: true

    - name: Ensure PostgreSQL user exists
      become_user: postgres
      shell: |
        psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ pg_user }}'" | grep -q 1 || \
        psql -c "CREATE USER {{ pg_user }} WITH PASSWORD '{{ pg_pass }}';"

    - name: Ensure blockscout database exists
      become_user: postgres
      shell: |
        psql -tAc "SELECT 1 FROM pg_database WHERE datname='{{ pg_db }}'" | grep -q 1 || \
        psql -c "CREATE DATABASE {{ pg_db }} OWNER {{ pg_user }};"

    - name: Grant all privileges on the database to the user
      become_user: postgres
      shell: |
        psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ pg_db }} TO {{ pg_user }};"
