[package]
name = "ethrex-dev"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true
license.workspace = true

[dependencies]
ethrex-blockchain.workspace = true
ethrex-common.workspace = true
ethrex-storage.workspace = true
ethrex-config.workspace = true

spawned-concurrency.workspace = true
tokio = { workspace = true, features = ["rt", "time", "sync"] }
tracing.workspace = true
thiserror.workspace = true
ethereum-types.workspace = true
bytes.workspace = true
serde_json.workspace = true
secp256k1.workspace = true
hex.workspace = true

[lib]
path = "./lib.rs"

[lints]
workspace = true
